package me.arunajayan.entriverselibrary.theme.colors

import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color

@Immutable
public data class EntriverseColors internal constructor(
    public val lightMode: Boolean,
    public val referenceColors: ReferenceColors,
)

@Immutable
public data class ReferenceColors internal constructor(
    public val backgroundDefault: Color,
    public val backgroundGrey: Color,
    public val blueContainer: Color,
    public val blueHover: Color,
    public val blueIcon: Color,
    public val blueOutline: Color,
    public val brownIcon: Color,
    public val defaultIcon: Color,
    public val disabledIcon: Color,
    public val disabledText: Color,
    public val entriBlue: Color,
    public val fixedBlack: Color,
    public val fixedPureBlack: Color,
    public val fixedWhite: Color,
    public val goldIcon: Color,
    public val greenIcon: Color,
    public val invertedIcon: Color,
    public val invertedText: Color,
    public val linkText: Color,
    public val linkTextHover: Color,
    public val linkTextVisited: Color,
    public val onBlue: Color,
    public val onBlueContainer: Color,
    public val orangeIcon: Color,
    public val placeholderIcon: Color,
    public val placeholderText: Color,
    public val primaryContainer: Color,
    public val primaryText: Color,
    public val purpleIcon: Color,
    public val secondaryContainer: Color,
    public val secondaryIcon: Color,
    public val subtext: Color,
    public val surfaceOutline: Color,
    public val surfaceOutlineDisabled: Color,
    public val timestampText: Color,
    public val yellowIcon: Color,
    public val entriGreen: Color,
    public val onGreen: Color,
    public val greenContainer: Color,
    public val onGreenContainer: Color,
    public val greenHover: Color,
    public val entriPurple:Color,
    public val onPurple:Color,
    public val purpleContainer:Color,
    public val onPurpleContainer:Color,
    public val purpleHover:Color,
    public val entriOrange:Color,
    public val onOrange:Color,
    public val orangeContainer:Color,
    public val onOrangeContainer:Color,
    public val orangeHover:Color,
    public val entriYellow:Color,
    public val onYellow:Color,
    public val yellowContainer:Color,
    public val onYellowContainer:Color,
    public val yellowHover:Color,
    public val entriBrown:Color,
    public val onBrown:Color,
    public val brownContainer:Color,
    public val onBrownContainer:Color,
    public val brownHover:Color,
    public val entriGold:Color,
    public val onGold:Color,
    public val goldContainer:Color,
    public val onGoldContainer:Color,
    public val goldHover:Color,
    public val errorColor:Color,
    public val onError:Color,
    public val errorTextColor:Color,
    public val errorOutlineColor:Color,
    public val errorContainer:Color,
    public val onErrorContainer:Color,
    public val errorHover:Color,
    public val successColor:Color,
    public val onSuccess:Color,
    public val successTextColor:Color,
    public val successOutlineColor:Color,
    public val successContainer:Color,
    public val onSuccessContainer:Color,
    public val successHover:Color,
)
