package entriverse.shared.theme.colors

import androidx.compose.runtime.Composable
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.runtime.staticCompositionLocalOf

@Composable
internal fun ProvideEntriverseColors(colors: EntriverseColors, content: @Composable () -> Unit) {
    CompositionLocalProvider(LocalEntriverseColors provides colors, content = content)
}

internal val LocalEntriverseColors = staticCompositionLocalOf { lightColors }

internal val lightColors = with(entriverse.shared.Entriverse.palette) {
    EntriverseColors(
        lightMode = true,
        referenceColors = ReferenceColors(
            backgroundDefault = grey1400,
            backgroundGrey = pureBlack,
            primaryContainer = grey1100,
            secondaryContainer = grey1200,
            surfaceOutline = grey600,
            surfaceOutlineDisabled = grey1300,
            blueOutline = blue200,
            primaryText = grey30,
            subtext = grey70,
            placeholderText = grey90,
            timestampText = grey100,
            invertedText = grey1000,
            disabledText = grey300,
            linkText = blue100,
            linkTextHover = blue300,
            linkTextVisited = purple200,
            defaultIcon = grey30,
            secondaryIcon = grey70,
            invertedIcon = grey1000,
            placeholderIcon = grey100,
            disabledIcon = grey300,
            blueIcon = blue400,
            greenIcon = green400,
            purpleIcon = purple400,
            orangeIcon = orange400,
            yellowIcon = yellow400,
            brownIcon = brown400,
            goldIcon = gold400,
            fixedWhite = pureWhite,
            fixedBlack = grey1000,
            fixedPureBlack = pureBlack,
            entriBlue = blue400,
            onBlue = blue900,
            blueContainer = blue900,
            onBlueContainer = blue100,
            blueHover = blue300,
            entriGreen = green500,
            onGreen = pureWhite,
            greenContainer = green50,
            onGreenContainer = green800,
            greenHover = green800,
            entriPurple = purple500,
            onPurple = pureWhite,
            purpleContainer = purple50,
            onPurpleContainer = purple800,
            purpleHover = purple800,
            entriOrange = orange500,
            onOrange = grey1000,
            orangeContainer = orange50,
            onOrangeContainer = orange800,
            orangeHover = orange800,
            entriYellow = yellow500,
            onYellow = grey1000,
            yellowContainer = yellow50,
            onYellowContainer = yellow800,
            yellowHover = yellow800,
            entriBrown = brown500,
            onBrown = pureWhite,
            brownContainer = brown50,
            onBrownContainer = brown800,
            brownHover = brown800,
            entriGold = gold500,
            onGold = grey1000,
            goldContainer = gold50,
            onGoldContainer = gold800,
            goldHover = gold800,
            errorColor = red500,
            onError = pureWhite,
            errorTextColor = red500,
            errorOutlineColor = red800,
            errorContainer = red50,
            onErrorContainer = red800,
            errorHover = red800,
            successColor = green500,
            onSuccess = pureWhite,
            successTextColor = green500,
            successOutlineColor = green800,
            successContainer = green50,
            onSuccessContainer = green800,
            successHover = green800
        ),
        componentColors = ComponentColors(
            buttonFilledDefault = blue700,
            buttonTonalDefault = blue50,
            buttonTonalDefaultText = blue800,
            buttonTonalDisabled = grey30,
            buttonTonalDisabledText = grey40,
            buttonTonalDisabledIcon = grey40,
            buttonTonalHover = blue100,
            buttonTonalHoverText = blue800,
            buttonTonalHoverIcon = blue800,
            buttonFilledDefaultIcon = pureWhite,
            buttonOutlinedBorderDefault = blue700,
            buttonOutlinedDefault = blue200,
            buttonOutlinedHover = blue100,
            buttonOutlinedHoverText = blue800,
            buttonOutlinedHoverIcon = blue800,
            buttonTextDefault = blue800,
            buttonTextHover = blue900,
            buttonTextDisabled = grey50,
            buttonBackgroundDefault = blue500,
            buttonBackgroundHover = blue400,
            buttonBackgroundDisabled = grey200,
            buttonTextSecondary = blue600,
            buttonBackgroundSecondary = grey100,
            buttonTextTertiary = grey600,
            buttonBackgroundTertiary = grey300,
            buttonTonalPressed = blue600,
            buttonTonalPressedText = blue700,
            buttonTextOnDark = pureWhite,
            buttonBackgroundOnDark = blue400,
            linkDefault = blue500,
            linkHover = blue400,
            linkVisited = blue600,

            fabBackground = blue500,
            fabIconDefault = pureWhite,
            fabIconDisabled = grey300,
            fabBackgroundDisabled = grey200,

            checkboxUnchecked = grey300,
            checkboxChecked = blue500,
            checkboxDisabled = grey200,
            checkboxTextChecked = pureWhite,
            checkboxTextUnchecked = grey500,

            switchUnchecked = grey400,
            switchChecked = blue600,
            switchDisabled = grey300,
            switchTrackUnchecked = grey200,
            switchTrackChecked = blue400,

            textPrimary = blue700,
            textSecondary = grey600,
            textTertiary = grey400,
            textDisabled = grey300,

            backgroundDefault = pureWhite,
            backgroundSecondary = grey50,
            backgroundTertiary = grey100,

            borderDefault = grey200,
            borderFocus = blue700,
            borderDisabled = grey300,

            errorText = red600,
            successText = green600,
            warningText = yellow600,
            infoText = blue600,

            containerBackground = grey50,
            containerBorder = grey200,

            inputTextDefault = blue700,
            inputTextPlaceholder = grey400,
            inputTextFocus = blue500,
            inputTextDisabled = grey200,

            labelTextDefault = grey700,
            labelTextFocus = blue500,
            labelTextDisabled = grey300,

            leadingIconDefault = grey500,
            leadingIconFocus = blue500,
            leadingIconDisabled = grey300,

            supportingTextDefault = grey400,
            supportingTextFocus = blue600,
            supportingTextDisabled = grey200,

            trailingIconDefault = grey500,
            trailingIconFocus = blue500,
            trailingIconDisabled = grey300,

            navigationBarBackground = blue700,
            navigationBarIconDefault = grey50,
            navigationBarIconSelected = blue500,

            radioButtonUnchecked = grey300,
            radioButtonChecked = blue500,
            radioButtonDisabled = grey200,
            radioButtonTextChecked = pureWhite,
            radioButtonTextUnchecked = grey500,

            segmentedButtonBackgroundDefault = blue600,
            segmentedButtonBackgroundSelected = blue700,
            segmentedButtonTextDefault = grey100,
            segmentedButtonTextSelected = pureWhite,

            selectionBackground = blue200,
            selectionText = blue700,

            sliderTrackDefault = grey200,
            sliderTrackActive = blue500,
            sliderThumb = blue700,
            sliderThumbDisabled = grey300,

            snackbarBackground = blue700,
            snackbarText = pureWhite,
            snackbarActionText = blue500,

            tabsBackgroundDefault = grey50,
            tabsBackgroundSelected = blue500,
            tabsTextDefault = grey700,
            tabsTextSelected = blue700,

            tooltipBackground = blue600,
            tooltipText = pureWhite
        ),
        materialColors = MaterialColors(
            primary = LightPrimary,
            onPrimary = LightOnPrimary,
            primaryContainer = LightPrimaryContainer,
            onPrimaryContainer = LightOnPrimaryContainer,
            inversePrimary = LightInversePrimary,
            secondary = LightSecondary,
            onSecondary = LightOnSecondary,
            secondaryContainer = LightSecondaryContainer,
            onSecondaryContainer = LightOnSecondaryContainer,
            tertiary = LightTertiary,
            onTertiary = LightOnTertiary,
            tertiaryContainer = LightTertiaryContainer,
            onTertiaryContainer = LightOnTertiaryContainer,
            background = LightBackground,
            onBackground = LightOnBackground,
            surface = LightSurface,
            onSurface = LightOnSurface,
            surfaceVariant = LightSurfaceVariant,
            onSurfaceVariant = LightOnSurfaceVariant,
            surfaceTint = LightSurfaceTint,
            inverseSurface = LightInverseSurface,
            inverseOnSurface = LightInverseOnSurface,
            error = LightError,
            onError = LightOnError,
            errorContainer = LightErrorContainer,
            onErrorContainer = LightOnErrorContainer,
            outline = LightOutline,
            outlineVariant = LightOutlineVariant,
            scrim = LightScrim
        )
    )
}

internal val darkColors = with(entriverse.shared.Entriverse.palette) {
    EntriverseColors(
        lightMode = false,
        referenceColors = ReferenceColors(
            backgroundDefault = blue100,
            backgroundGrey = grey30,
            primaryContainer = pureWhite,
            secondaryContainer = grey20,
            surfaceOutline = grey30,
            surfaceOutlineDisabled = grey10,
            blueOutline = blue700,
            primaryText = grey1000,
            subtext = grey80,
            placeholderText = grey60,
            timestampText = grey50,
            invertedText = grey30,
            disabledText = grey40,
            linkText = blue700,
            linkTextHover = blue800,
            linkTextVisited = purple700,
            defaultIcon = grey1000,
            secondaryIcon = grey80,
            invertedIcon = grey30,
            placeholderIcon = grey50,
            disabledIcon = grey40,
            blueIcon = blue500,
            greenIcon = green500,
            purpleIcon = purple500,
            orangeIcon = orange500,
            yellowIcon = yellow500,
            brownIcon = brown500,
            goldIcon = gold500,
            fixedWhite = pureWhite,
            fixedBlack = grey1000,
            fixedPureBlack = pureBlack,
            entriBlue = blue500,
            onBlue = pureWhite,
            blueContainer = blue50,
            onBlueContainer = blue800,
            blueHover = blue800,
            entriGreen = green400,
            onGreen = green900,
            greenContainer = green900,
            onGreenContainer = green100,
            greenHover = green300,
            entriPurple = purple400,
            onPurple = purple900,
            purpleContainer = purple900,
            onPurpleContainer = purple100,
            purpleHover = purple300,
            entriOrange = orange400,
            onOrange = orange900,
            orangeContainer = orange900,
            onOrangeContainer = orange100,
            orangeHover = orange300,
            entriYellow = yellow400,
            onYellow = yellow900,
            yellowContainer = yellow900,
            onYellowContainer = yellow100,
            yellowHover = yellow300,
            entriBrown = brown400,
            onBrown = brown900,
            brownContainer = brown900,
            onBrownContainer = brown100,
            brownHover = brown300,
            entriGold = gold400,
            onGold = gold900,
            goldContainer = gold900,
            onGoldContainer = gold100,
            goldHover = gold300,
            errorColor = red400,
            onError = red900,
            errorTextColor = red400,
            errorOutlineColor = red100,
            errorContainer = red900,
            onErrorContainer = red100,
            errorHover = red300,
            successColor = green400,
            onSuccess = green900,
            successTextColor = green400,
            successOutlineColor = green100,
            successContainer = green900,
            onSuccessContainer = green100,
            successHover = green300,
        ),
        componentColors = ComponentColors(
            buttonFilledDefault = blue200,
            buttonTonalDefault = grey200,
            buttonTonalDefaultText = grey30,
            buttonTonalDisabled = grey600,
            buttonTonalDisabledText = grey100,
            buttonTonalDisabledIcon = grey100,
            buttonTonalHover = grey100,
            buttonTonalHoverText = grey30,
            buttonTonalHoverIcon = grey30,
            buttonFilledDefaultIcon = blue900,
            buttonOutlinedBorderDefault = blue200,
            buttonOutlinedDefault = blue300,
            buttonOutlinedHover = blue500,
            buttonOutlinedHoverText = blue900,
            buttonOutlinedHoverIcon = blue900,
            buttonTextDefault = grey50,
            buttonTextHover = grey200,
            buttonTextDisabled = grey400,
            buttonBackgroundDefault = blue600,
            buttonBackgroundHover = blue700,
            buttonBackgroundDisabled = grey800,
            buttonTextSecondary = grey200,
            buttonBackgroundSecondary = grey700,
            buttonTextTertiary = grey400,
            buttonBackgroundTertiary = grey600,
            buttonTonalPressed = grey500,
            buttonTonalPressedText = grey400,
            buttonTextOnDark = pureWhite,
            buttonBackgroundOnDark = grey800,
            linkDefault = grey50,
            linkHover = grey100,
            linkVisited = grey400,

            fabBackground = blue400,
            fabIconDefault = pureWhite,
            fabIconDisabled = grey500,
            fabBackgroundDisabled = grey600,

            checkboxUnchecked = grey600,
            checkboxChecked = blue400,
            checkboxDisabled = grey500,
            checkboxTextChecked = pureWhite,
            checkboxTextUnchecked = grey700,

            switchUnchecked = grey600,
            switchChecked = blue700,
            switchDisabled = grey400,
            switchTrackUnchecked = grey300,
            switchTrackChecked = blue500,

            textPrimary = pureWhite,
            textSecondary = grey300,
            textTertiary = grey500,
            textDisabled = grey600,

            backgroundDefault = grey900,
            backgroundSecondary = grey800,
            backgroundTertiary = grey700,

            borderDefault = grey600,
            borderFocus = blue500,
            borderDisabled = grey700,

            errorText = red700,
            successText = green700,
            warningText = yellow700,
            infoText = blue700,

            containerBackground = grey800,
            containerBorder = grey600,

            inputTextDefault = pureWhite,
            inputTextPlaceholder = grey500,
            inputTextFocus = blue500,
            inputTextDisabled = grey700,

            labelTextDefault = grey400,
            labelTextFocus = blue500,
            labelTextDisabled = grey600,

            leadingIconDefault = grey500,
            leadingIconFocus = blue500,
            leadingIconDisabled = grey700,

            supportingTextDefault = grey400,
            supportingTextFocus = blue600,
            supportingTextDisabled = grey600,

            trailingIconDefault = grey500,
            trailingIconFocus = blue500,
            trailingIconDisabled = grey700,

            navigationBarBackground = blue900,
            navigationBarIconDefault = grey50,
            navigationBarIconSelected = blue500,

            radioButtonUnchecked = grey500,
            radioButtonChecked = blue400,
            radioButtonDisabled = grey600,
            radioButtonTextChecked = pureWhite,
            radioButtonTextUnchecked = grey700,

            segmentedButtonBackgroundDefault = blue600,
            segmentedButtonBackgroundSelected = blue700,
            segmentedButtonTextDefault = grey100,
            segmentedButtonTextSelected = pureWhite,

            selectionBackground = blue300,
            selectionText = blue700,

            sliderTrackDefault = grey600,
            sliderTrackActive = blue500,
            sliderThumb = blue700,
            sliderThumbDisabled = grey400,

            snackbarBackground = blue900,
            snackbarText = pureWhite,
            snackbarActionText = blue500,

            tabsBackgroundDefault = grey700,
            tabsBackgroundSelected = blue500,
            tabsTextDefault = grey400,
            tabsTextSelected = blue700,

            tooltipBackground = blue700,
            tooltipText = pureWhite
        ),
        materialColors = MaterialColors(
            primary = DarkPrimary,
            onPrimary = DarkOnPrimary,
            primaryContainer = DarkPrimaryContainer,
            onPrimaryContainer = DarkOnPrimaryContainer,
            inversePrimary = DarkInversePrimary,
            secondary = DarkSecondary,
            onSecondary = DarkOnSecondary,
            secondaryContainer = DarkSecondaryContainer,
            onSecondaryContainer = DarkOnSecondaryContainer,
            tertiary = DarkTertiary,
            onTertiary = DarkOnTertiary,
            tertiaryContainer = DarkTertiaryContainer,
            onTertiaryContainer = DarkOnTertiaryContainer,
            background = DarkBackground,
            onBackground = DarkOnBackground,
            surface = DarkSurface,
            onSurface = DarkOnSurface,
            surfaceVariant = DarkSurfaceVariant,
            onSurfaceVariant = DarkOnSurfaceVariant,
            surfaceTint = DarkSurfaceTint,
            inverseSurface = DarkInverseSurface,
            inverseOnSurface = DarkInverseOnSurface,
            error = DarkError,
            onError = DarkOnError,
            errorContainer = DarkErrorContainer,
            onErrorContainer = DarkOnErrorContainer,
            outline = DarkOutline,
            outlineVariant = DarkOutlineVariant,
            scrim = DarkScrim
        )
    )
}
