package entriverse.shared.theme.colors

import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color

@Immutable
data class EntriverseColors internal constructor(
    val lightMode: Boolean,
    val referenceColors: ReferenceColors,
)

@Immutable
data class ReferenceColors internal constructor(
    val backgroundDefault: Color,
    val backgroundGrey: Color,
    val blueContainer: Color,
    val blueHover: Color,
    val blueIcon: Color,
    val blueOutline: Color,
    val brownIcon: Color,
    val defaultIcon: Color,
    val disabledIcon: Color,
    val disabledText: Color,
    val entriBlue: Color,
    val fixedBlack: Color,
    val fixedPureBlack: Color,
    val fixedWhite: Color,
    val goldIcon: Color,
    val greenIcon: Color,
    val invertedIcon: Color,
    val invertedText: Color,
    val linkText: Color,
    val linkTextHover: Color,
    val linkTextVisited: Color,
    val onBlue: Color,
    val onBlueContainer: Color,
    val orangeIcon: Color,
    val placeholderIcon: Color,
    val placeholderText: Color,
    val primaryContainer: Color,
    val primaryText: Color,
    val purpleIcon: Color,
    val secondaryContainer: Color,
    val secondaryIcon: Color,
    val subtext: Color,
    val surfaceOutline: Color,
    val surfaceOutlineDisabled: Color,
    val timestampText: Color,
    val yellowIcon: Color,
    val entriGreen: Color,
    val onGreen: Color,
    val greenContainer: Color,
    val onGreenContainer: Color,
    val greenHover: Color,
    val entriPurple: Color,
    val onPurple: Color,
    val purpleContainer: Color,
    val onPurpleContainer: Color,
    val purpleHover: Color,
    val entriOrange: Color,
    val onOrange: Color,
    val orangeContainer: Color,
    val onOrangeContainer: Color,
    val orangeHover: Color,
    val entriYellow: Color,
    val onYellow: Color,
    val yellowContainer: Color,
    val onYellowContainer: Color,
    val yellowHover: Color,
    val entriBrown: Color,
    val onBrown: Color,
    val brownContainer: Color,
    val onBrownContainer: Color,
    val brownHover: Color,
    val entriGold: Color,
    val onGold: Color,
    val goldContainer: Color,
    val onGoldContainer: Color,
    val goldHover: Color,
    val errorColor: Color,
    val onError: Color,
    val errorTextColor: Color,
    val errorOutlineColor: Color,
    val errorContainer: Color,
    val onErrorContainer: Color,
    val errorHover: Color,
    val successColor: Color,
    val onSuccess: Color,
    val successTextColor: Color,
    val successOutlineColor: Color,
    val successContainer: Color,
    val onSuccessContainer: Color,
    val successHover: Color,
)
