package entriverse.shared.theme.colors

fun createLightColors(): EntriverseColors {
    return EntriverseColors(
        lightMode = true,
        referenceColors = createLightReferenceColors(),
        componentColors = createLightComponentColors(),
        materialColors = createLightMaterialColors()
    )
}

fun createLightReferenceColors(): ReferenceColors {
    with(entriverse.shared.Entriverse.palette) {
        return ReferenceColors(
            backgroundDefault = pureWhite,
            backgroundGrey = grey30,
            primaryContainer = pureWhite,
            secondaryContainer = grey20,
            surfaceOutline = grey30,
            surfaceOutlineDisabled = grey10,
            blueOutline = blue700,
            primaryText = grey1000,
            subtext = grey80,
            placeholderText = grey60,
            timestampText = grey50,
            invertedText = grey30,
            disabledText = grey40,
            linkText = blue700,
            linkTextHover = blue800,
            linkTextVisited = purple700,
            defaultIcon = grey1000,
            secondaryIcon = grey80,
            invertedIcon = grey30,
            placeholderIcon = grey50,
            disabledIcon = grey40,
            blueIcon = blue500,
            greenIcon = green500,
            purpleIcon = purple500,
            orangeIcon = orange500,
            yellowIcon = yellow500,
            brownIcon = brown500,
            goldIcon = gold500,
            fixedWhite = pureWhite,
            fixedBlack = grey1000,
            fixedPureBlack = pureBlack,
            entriBlue = blue500,
            onBlue = pureWhite,
            blueContainer = blue50,
            onBlueContainer = blue800,
            blueHover = blue800,
            entriGreen = green400,
            onGreen = green900,
            greenContainer = green900,
            onGreenContainer = green100,
            greenHover = green300,
            entriPurple = purple400,
            onPurple = purple900,
            purpleContainer = purple900,
            onPurpleContainer = purple100,
            purpleHover = purple300,
            entriOrange = orange400,
            onOrange = orange900,
            orangeContainer = orange900,
            onOrangeContainer = orange100,
            orangeHover = orange300,
            entriYellow = yellow400,
            onYellow = yellow900,
            yellowContainer = yellow900,
            onYellowContainer = yellow100,
            yellowHover = yellow300,
            entriBrown = brown400,
            onBrown = brown900,
            brownContainer = brown900,
            onBrownContainer = brown100,
            brownHover = brown300,
            entriGold = gold400,
            onGold = gold900,
            goldContainer = gold900,
            onGoldContainer = gold100,
            goldHover = gold300,
            errorColor = red400,
            onError = red900,
            errorTextColor = red400,
            errorOutlineColor = red100,
            errorContainer = red900,
            onErrorContainer = red100,
            errorHover = red300,
            successColor = green400,
            onSuccess = green900,
            successTextColor = green400,
            successOutlineColor = green100,
            successContainer = green900,
            onSuccessContainer = green100,
            successHover = green300,
        )
    }
}

fun createLightComponentColors(): ComponentColors {
    with(entriverse.shared.Entriverse.palette) {
        return ComponentColors(
            buttonColors = ButtonColors(
                buttonFilledDefault = blue700,
                buttonFilledDefaultText = pureWhite,
                buttonFilledDisabledText = grey40,
                buttonFilledDisabled = grey30,
                buttonFilledHover = blue800,
                buttonFilledHoverText = pureWhite,
                buttonFilledFocused = blue800,
                buttonFilledFocusedText = pureWhite,
                buttonFilledFocusedBorder = blue100,

                buttonTonalDefault = blue50,
                buttonTonalDefaultText = blue800,
                buttonTonalDisabled = grey30,
                buttonTonalDisabledText = grey40,
                buttonTonalHover = blue100,
                buttonTonalHoverText = blue800,
                buttonTonalFocused = blue100,
                buttonTonalFocusedText = blue800,
                buttonTonalFocusedBorder = blue300,

                buttonFilledDefaultIcon = pureWhite,
                buttonFilledDisabledIcon = grey40,
                buttonFilledHoverIcon = pureWhite,
                buttonFilledFocusedIcon = pureWhite,

                buttonTonalDefaultIcon = blue800,
                buttonTonalDisabledIcon = grey40,
                buttonTonalHoverIcon = blue800,
                buttonTonalFocusedIcon = blue800,

                buttonOutlinedBorderDefault = blue700,
                buttonOutlinedDefaultText = blue800,
                buttonOutlinedDefaultIcon = blue800,
                buttonOutlinedBorderDisabled = grey20,
                buttonOutlinedDisabledText = grey40,
                buttonOutlinedDisabledIcon = grey40,
                buttonOutlinedFillHover = blue50,
                buttonOutlinedHoverText = blue800,
                buttonOutlinedHoverIcon = blue800,
                buttonOutlinedFillFocused = blue100,
                buttonOutlinedFocusedText = blue800,
                buttonOutlinedFocusedIcon = blue800,
                buttonOutlinedBorderHover = blue700,
                buttonOutlinedBorderFocused = blue300,

                buttonSecondaryOutlinedBorderDefault = grey40,
                buttonSecondaryOutlinedDefaultText = grey1000,
                buttonSecondaryOutlinedDefaultIcon = grey1000,
                buttonSecondaryOutlinedBorderDisabled = grey20,
                buttonSecondaryOutlinedDisabledText = grey40,
                buttonSecondaryOutlinedDisabledIcon = grey40,
                buttonSecondaryOutlinedFillHover = grey20,
                buttonSecondaryOutlinedBorderHover = grey30,
                buttonSecondaryOutlinedHoverText = grey1000,
                buttonSecondaryOutlinedHoverIcon = grey1000,
                buttonSecondaryOutlinedFillFocused = grey20,
                buttonSecondaryOutlinedBorderFocused = grey40,
                buttonSecondaryOutlinedFocusedText = grey1000,
                buttonSecondaryOutlinedFocusedIcon = grey1000,

                buttonDestructiveDefault = red700,
                buttonDestructiveDefaultText = pureWhite,
                buttonDestructiveDefaultIcon = pureWhite,
                buttonDestructiveDisabled = grey30,
                buttonDestructiveDisabledText = grey40,
                buttonDestructiveDisabledIcon = grey40,
                buttonDestructiveHover = red800,
                buttonDestructiveHoverText = pureWhite,
                buttonDestructiveHoverIcon = pureWhite,
                buttonDestructiveFocused = red800,
                buttonDestructiveFocusedText = pureWhite,
                buttonDestructiveFocusedIcon = pureWhite,
                buttonDestructiveFocusedBorder = red100,

                buttonSuccessDefault = green600,
                buttonSuccessDefaultText = pureWhite,
                buttonSuccessDefaultIcon = pureWhite,
                buttonSuccessDisabled = grey30,
                buttonSuccessDisabledText = grey40,
                buttonSuccessDisabledIcon = grey40,
                buttonSuccessHover = green800,
                buttonSuccessHoverText = pureWhite,
                buttonSuccessHoverIcon = pureWhite,
                buttonSuccessFocused = green800,
                buttonSuccessFocusedText = pureWhite,
                buttonSuccessFocusedIcon = pureWhite,
                buttonSuccessFocusedBorder = green100
            ), fabColors = FabColors(
                fabContainerColor = orange100,
                fabTextColor = orange900,
                fabIconColor = orange900,
                fabHoverColor = orange200,
            ), checkboxColors = CheckboxColors(
                checkboxActive = blue700,
                checkboxInactive = grey50,
                checkboxInactiveHover = grey80,
                checkboxActiveHover = blue800,
                checkboxDisabled = grey40
            ), inputColors = InputColors(
                cursorColor = blue500,
                inputTextActive = grey1000,
                inputTextDisabled = grey40,
                inputTextPlaceholder = grey80,
                inputContainerSuccess =green500,
                inputContainerError = red800,
                inputContainerFocused = blue700,
                inputContainerOutline = grey50,
            ), labelColors = LabelColors(
                labelText = grey60,
                labelTextFocused = blue500,
                labelTextDisabled = grey40,
                labelBgColorDefault = pureWhite,
                labelBgColorPrimaryContainer = pureWhite,
                labelTextError = red500,
                labelTextSuccess = green500,
            ), iconColors = IconColors(
                leadingIcon = grey1000,
                leadingIconFocused = blue500,
                leadingIconDisabled = grey40,
                leadingIconError = red500,
                leadingIconSuccess = green500,
                leadingIconPlaceholder = grey50,
                trailingIcon = grey1000,
                trailingIconFocused = blue500,
                trailingIconError = red500,
                trailingIconSuccess = green500,
                trailingIconDisabled = grey40,
                trailingIconSecondary = grey80,
                trailingIconPlaceholder = grey50,
            ), supportingTextColors = SupportingTextColors(
                supportingText = grey60,
                supportingTextError = red500,
                supportingTextSuccess = green500,
                supportingTextDisabled = grey40,
            ), navigationBarColors = NavigationBarColors(
                navContainerColor = pureWhite,
                navTextColor = white, // No Light Mode value provided
                navActiveIndicator = blue50,
                navIconActive = blue700,
                navIconInactive = grey80,
                navPremiumIconActive = purple500,
                navDividerColor = grey30,
            ), radioButtonColors = RadioButtonColors(
                radioActive = blue700,
                radioInactiveHover = grey80,
                radioActiveHover = blue800,
                radioDisabled = grey40,
                radioInactive = grey50,
            ), segmentedButtonColors = SegmentedButtonColors(
                segmentedActive = blue50,
                segmentedActiveOutline = blue700,
                segmentedInactiveContainer = pureWhite,
                segmentedInactiveOutline = grey30,
                segmentedActiveText = blue800,
                segmentedActiveIcon = blue800,
                segmentedInactiveIcon = grey1000,
                segmentedInactiveText = grey1000,
                segmentedBg = pureWhite,
            ), sliderColors = SliderColors(
                sliderValueContainerBg = grey1100,
                sliderValueText = grey30,
                sliderHandleContainerBg = pureWhite,
                sliderHandle = blue500,
                sliderInactiveTrack = blue50,
                sliderActiveTrack = blue500,
                sliderStopIndicatorInactive = fixedBlackLevel2,
                sliderDisabledTrack = grey1000,
                sliderHandleDisabled = grey1000,
                sliderHandleDisabledContainer = pureWhite,
                sliderStopIndicatorActive = fixedWhiteLevel2,
                sliderStopIndicatorDisabled = fixedBlackLevel2,
            ), snackBarColors = SnackbarColors(
                snackbarBgDefault = grey1400,
                snackbarText = grey30,
                snackbarPrimaryCta = blue200,
            ), tabsColors = TabsColors(
                secondaryTabActiveText = grey1000,
                secondaryTabInactiveText = grey80,
                secondaryTabIndicator = blue500,
                secondaryTabDivider = grey30,
                secondaryTabBgColor = pureWhite,
                secondaryTabHover = grey20,
            ), tooltipColors = TooltipColors(
                tooltipBgDefault = grey1400,
                tooltipBgGrey = grey1100,
                tooltipPrimaryText = grey30,
                tooltipSubtext = grey40,
                tooltipPrimaryCta = blue200,
                tooltipSecondaryCta = grey50,
            ), selectionColors = SelectionColors(
                selectionActive = blue50,
                selectionInactive = grey20,
                selectionText = grey1000,
                selectionOutlineActive = blue700,
                selectionSubtext = grey80,
                selectionProgressBarBg = darkLevel1,
                selectionProgressIndicator = green500,
                selectionDisabledText = grey50,
                selectionDisabled = grey40,
                selectionGoldActive = gold50,
                selectionGoldOutlineActive = gold500,
                selectionOutlineInactive = grey30,
                selectionTextGold = gold800,
            )
        )
    }
}

fun createLightMaterialColors(): MaterialColors {
    with(entriverse.shared.Entriverse.palette) {
        return MaterialColors(
            primary = LightPrimary,
            onPrimary = LightOnPrimary,
            primaryContainer = LightPrimaryContainer,
            onPrimaryContainer = LightOnPrimaryContainer,
            inversePrimary = LightInversePrimary,
            secondary = LightSecondary,
            onSecondary = LightOnSecondary,
            secondaryContainer = LightSecondaryContainer,
            onSecondaryContainer = LightOnSecondaryContainer,
            tertiary = LightTertiary,
            onTertiary = LightOnTertiary,
            tertiaryContainer = LightTertiaryContainer,
            onTertiaryContainer = LightOnTertiaryContainer,
            background = LightBackground,
            onBackground = LightOnBackground,
            surface = LightSurface,
            onSurface = LightOnSurface,
            surfaceVariant = LightSurfaceVariant,
            onSurfaceVariant = LightOnSurfaceVariant,
            surfaceTint = LightSurfaceTint,
            inverseSurface = LightInverseSurface,
            inverseOnSurface = LightInverseOnSurface,
            error = LightError,
            onError = LightOnError,
            errorContainer = LightErrorContainer,
            onErrorContainer = LightOnErrorContainer,
            outline = LightOutline,
            outlineVariant = LightOutlineVariant,
            scrim = LightScrim
        )
    }
}
